=== pablohs1986/dam_ad2021/tema2B_JAXB/ad_clientes_jaxb/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
       <xs:element name="clientes">
              <xs:complexType>
                     <xs:sequence>
                            <xs:element name="cliente" maxOccurs="unbounded">
                                   <xs:complexType>
                                          <xs:sequence>
                                                 <xs:element name="apellido" type="tipoApellido" minOccurs="1" maxOccurs ="2"/>  
                                                 <xs:element name="direccion" type="tipoDireccion" minOccurs="1" maxOccurs="3"/>
                                                 <xs:element name="telefono">
                                                        <xs:simpleType>
                                                               <xs:restriction base="xs:string">
                                                                      <xs:maxLength value="20"/>
                                                               </xs:restriction>
                                                        </xs:simpleType>
                                                 </xs:element>
                                                 <xs:element name="nombre">
                                                        <xs:complexType>
                                                               <xs:attribute name="lenguaje"/>
                                                        </xs:complexType>
                                                 </xs:element>
                                          </xs:sequence>
                                   </xs:complexType>
                            </xs:element>
                     </xs:sequence>
              </xs:complexType>
       </xs:element>

     <!-- Definicion del tipo datos -->       
       <xs:complexType name="tipoDireccion">
              <xs:sequence>
                     <xs:element name="calle">
                            <xs:simpleType>
                                   <xs:restriction base="xs:string">
                                          <xs:maxLength value="30"/>
                                   </xs:restriction>
                            </xs:simpleType>
                     </xs:element>
                     <xs:element name="numero">
                            <xs:simpleType>
                                   <xs:restriction base="xs:string">
                                          <xs:maxLength value="30"/>
                                   </xs:restriction>
                            </xs:simpleType>
                     </xs:element>
                     <xs:element name="piso">
                            <xs:simpleType>
                                   <xs:restriction base="xs:int"/>
                            </xs:simpleType>
                     </xs:element>
                     <xs:element name="escalera">
                            <xs:simpleType>
                                   <xs:restriction base="xs:string">
                                          <xs:enumeration value="a"/>
                                          <xs:enumeration value="b"/>
                                          <xs:enumeration value="c"/>
                                   </xs:restriction>
                            </xs:simpleType>
                     </xs:element>
                     <xs:element name="cp">
                            <xs:simpleType>
                                   <xs:restriction base="xs:int">
                                          <xs:totalDigits value="5"/>
                                   </xs:restriction>
                            </xs:simpleType>
                     </xs:element>
                     <xs:element name="ciudad">
                            <xs:simpleType>
                                   <xs:restriction base="xs:string">
                                          <xs:maxLength value="30"/>
                                   </xs:restriction>
                            </xs:simpleType>
                     </xs:element>
              </xs:sequence>
       </xs:complexType>
       
<xs:simpleType name="tipoApellido">
              <xs:restriction base="xs:string">
                     <xs:maxLength value="20"/>
              </xs:restriction>
       </xs:simpleType>
</xs:schema>

=== pablohs1986/dam_ad2021/tema2C_JSON/ad_ejercicio2_json/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>

<clientes xsi:noNamespaceSchemaLocation="clientes.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<cliente>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>c</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>a</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>b</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<telefono>aaaaaaaaaaaaaaaaaaaa</telefono>
		<nombre>String</nombre>
	</cliente>
	<cliente>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>b</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>c</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>b</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<telefono>aaaaaaaaaaaaaaaaaaaa</telefono>
		<nombre>String</nombre>
	</cliente>
	<cliente>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<apellido>aaaaaaaaaaaaaaaaaaaa</apellido>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>c</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>c</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<direccion>
			<calle>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</calle>
			<numero>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</numero>
			<piso>0</piso>
			<escalera>b</escalera>
			<cp>12345</cp>
			<ciudad>aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa</ciudad>
		</direccion>
		<telefono>aaaaaaaaaaaaaaaaaaaa</telefono>
		<nombre>String</nombre>
	</cliente>
</clientes>
