=== pablohs1986/dam_ad2021/EXAMEN/ad_examen_jaxb_PabloHerrero/xml-resources/jaxb/FitnessBind/fitness2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Jose (A) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="fitness">
		<xs:annotation>
			<xs:documentation>Personal Fitness app</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="users">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="user">
								<xs:complexType>
									<xs:complexContent>
										<xs:extension base="userType">
											<xs:sequence>
												<xs:element name="favoriteExecises" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="exerciseType">
																<xs:sequence>
																	<xs:element name="date"/>
																</xs:sequence>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
												<xs:element name="asignedWorkouts" maxOccurs="unbounded">
													<xs:complexType>
														<xs:complexContent>
															<xs:extension base="workoutType">
																<xs:sequence>
																	<xs:element name="workoutDone" type="xs:boolean"/>
																</xs:sequence>
															</xs:extension>
														</xs:complexContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:extension>
									</xs:complexContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="workouts">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="workout" type="workoutType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="exerciseType">
		<xs:sequence>
			<xs:element name="exerciseName" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="URLVideo" type="xs:string"/>
			<xs:element name="duration" type="xs:int"/>
			<xs:element name="reps" type="xs:int"/>
			<xs:element name="calories" type="xs:int"/>
			<xs:element name="dificulty" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="workoutType">
		<xs:sequence>
			<xs:element name="workoutName" type="xs:string"/>
			<xs:element name="exercise" type="exerciseType" maxOccurs="unbounded"/>
			<xs:element name="totalCalories" type="xs:int"/>
			<xs:element name="difficulty" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="userType">
		<xs:sequence>
			<xs:element name="userID" type="xs:int"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="weight" type="xs:float"/>
			<xs:element name="height" type="xs:float"/>
			<xs:element name="imc" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== pablohs1986/dam_ad2021/EXAMEN/ad_examen_jaxb_PabloHerrero/fitness2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2021 (x64) (http://www.altova.com)-->
<fitness xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fitness2.xsd">
	<users>
		<user>
			<userID>1</userID>
			<name>Pablo</name>
			<weight>3.141590118408203125</weight>
			<height>3.141590118408203125</height>
			<imc>3.141590118408203125</imc>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
		</user>
		<user>
			<userID>2</userID>
			<name>String</name>
			<weight>3.141590118408203125</weight>
			<height>3.141590118408203125</height>
			<imc>3.141590118408203125</imc>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
		</user>
		<user>
			<userID>3</userID>
			<name>String</name>
			<weight>3.141590118408203125</weight>
			<height>3.141590118408203125</height>
			<imc>3.141590118408203125</imc>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<favoriteExecises>
				<exerciseName>String</exerciseName>
				<description>String</description>
				<URLVideo>String</URLVideo>
				<duration>0</duration>
				<reps>0</reps>
				<calories>0</calories>
				<dificulty>0</dificulty>
				<date>text</date>
			</favoriteExecises>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
					<URLVideo>String</URLVideo>
					<duration>0</duration>
					<reps>0</reps>
					<calories>0</calories>
					<dificulty>0</dificulty>
				</exercise>
				<totalCalories>0</totalCalories>
				<difficulty>0</difficulty>
				<workoutDone>true</workoutDone>
			</asignedWorkouts>
			<asignedWorkouts>
				<workoutName>String</workoutName>
				<exercise>
					<exerciseName>String</exerciseName>
					<description>String</description>
