=== pablohs1986/dam_ad2021/preparacionExamen1evaluacion/ejercicio4_jaxb/diccionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="diccionarioEspanol">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="palabra" type="palabraType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="palabraType">
		<xs:sequence>
			<xs:element name="grafia" type="xs:string"/>
			<xs:element name="fonetica" type="xs:string"/>
			<xs:element name="definicion" type="xs:string" maxOccurs="unbounded"/>
			<xs:element name="fechaInsercion" type="xs:date"/>
			<xs:element name="traducciones">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="traduccion" type="traduccionType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sinonimos">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="sinonimo" type="sinonimoType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="traduccionType">
		<xs:sequence>
			<xs:element name="idiomaTraduccion" type="xs:string"/>
			<xs:element name="grafia" type="xs:string"/>
			<xs:element name="fonetica" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sinonimoType">
		<xs:sequence>
			<xs:element name="grafia" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== pablohs1986/dam_ad2021/preparacionExamen1evaluacion/ad_ejercicio4_jaxb/diccionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<diccionarioEspanol xsi:noNamespaceSchemaLocation="diccionario.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<palabra>
		<grafia>String</grafia>
		<fonetica>String</fonetica>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<fechaInsercion>1967-08-13</fechaInsercion>
		<traducciones>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
		</traducciones>
		<sinonimos>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
		</sinonimos>
	</palabra>
	<palabra>
		<grafia>String</grafia>
		<fonetica>String</fonetica>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<fechaInsercion>1967-08-13</fechaInsercion>
		<traducciones>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
		</traducciones>
		<sinonimos>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
		</sinonimos>
	</palabra>
	<palabra>
		<grafia>String</grafia>
		<fonetica>String</fonetica>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<definicion>String</definicion>
		<fechaInsercion>1967-08-13</fechaInsercion>
		<traducciones>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
			<traduccion>
				<idiomaTraduccion>String</idiomaTraduccion>
				<grafia>String</grafia>
				<fonetica>String</fonetica>
			</traduccion>
		</traducciones>
		<sinonimos>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
			<sinonimo>
				<grafia>String</grafia>
			</sinonimo>
		</sinonimos>
	</palabra>
</diccionarioEspanol>
